"use client";

import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import ChartPanel from "../components/ChartPanel";
import KpiCard from "../components/KpiCard";
import ResultTable from "../components/ResultTable";
import SummaryRenderer from "../components/SummaryRenderer";

interface KpiItem {
  label?: string;
  title?: string;
  value: string | number;
  unit?: string;
  sub?: string;
}

interface AskResult {
  question: string;
  request_id?: string;
  plan?: Record<string, any>;
  frames?: Record<string, Record<string, any>[]>;
  insights?: string;
  kpis?: KpiItem[];
  chart?: Record<string, any>;
  log?: any[];
  sqls?: Array<[string, string]>;
  followups?: any[];
  merges?: Record<string, any>[];
  catalog?: Record<string, any>;
  reasoner_results?: Record<string, any>;
  needs_more?: boolean;
  followup_prompt?: string;
  required?: Record<string, any>;
  summary_obj?: Record<string, any>;
  view?: string;
  sql?: string;
  rows?: Record<string, any>[];
  narrative?: string;
  thinking?: string;
}

interface ModalState {
  type: null | "dataset" | "chart";
}

const EXAMPLES = [
  "How should RM time and meeting types be allocated to maximize profitability?",
  "declining mandates and why",
  "compare revenue and sentiment by RM in 2024 - based on meeting notes sentiment and revenue generated by RM that year",
  "Top 5 RMs in 2025 vs 2024 by performance",
];

const STAGES = ["Planning", "Fetching", "Linking", "Summarizing"];
const LONG_RUNNING_STAGES = ["provisioning", "initializing"];

// Mapping of stage names to user-friendly messages
const STAGE_MESSAGES: Record<string, string> = {
  provisioning: "Provisioning Engine",
  initializing: "Initializing Data Index",
};

export default function Home() {
  const [question, setQuestion] = useState("");
  const [result, setResult] = useState<AskResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeFrame, setActiveFrame] = useState("");
  const [activeGraphFrame, setActiveGraphFrame] = useState("");
  const [currentStage, setCurrentStage] = useState("planning");
  const [modal, setModal] = useState<ModalState>({ type: null });
  const [leftColWidth, setLeftColWidth] = useState(33);
  const [rightColWidth, setRightColWidth] = useState(33);
  const [isDragging, setIsDragging] = useState<string | null>(null);
  const [mobileTab, setMobileTab] = useState<"data" | "summary" | "chart">("summary");
  const [initializationStage, setInitializationStage] = useState<string | null>(null);
  const [thinkingVisible, setThinkingVisible] = useState(false);
  const [stageThinking, setStageThinking] = useState("");
  const [requestId, setRequestId] = useState<string | null>(null);
  const [viewportWidth, setViewportWidth] = useState(0);

  const apiUrl = useMemo(() => {
    const envUrl = process.env.NEXT_PUBLIC_API_URL;
    if (envUrl) return envUrl;
    if (typeof window !== "undefined") return window.location.origin;
    return "http://localhost:8000";
  }, []);

  useEffect(() => {
    if (result?.frames) {
      const keys = Object.keys(result.frames);
      setActiveFrame(keys[0] || "");
    } else {
      setActiveFrame("");
    }
  }, [result]);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const update = () => setViewportWidth(window.innerWidth);
    update();
    window.addEventListener("resize", update);
    return () => window.removeEventListener("resize", update);
  }, []);

  useEffect(() => {
    if (result?.frames) {
      const keys = Object.keys(result.frames).filter((key) => key.startsWith("graph:"));
      setActiveGraphFrame(keys[0] || "");
    } else {
      setActiveGraphFrame("");
    }
  }, [result]);

  useEffect(() => {
    if (!loading) {
      setCurrentStage("planning");
      setInitializationStage(null);
      return;
    }

    // Poll for stage updates every 200ms while loading
    const pollInterval = setInterval(async () => {
      try {
        const rid = requestId ? `?request_id=${encodeURIComponent(requestId)}` : "";
        const resp = await fetch(`${apiUrl}/api/stages${rid}`);
        if (resp.ok) {
          const data = await resp.json();
          const newStage = data.stage || "planning";
          setCurrentStage(newStage);
          if (typeof data.thinking === "string") {
            setStageThinking(data.thinking);
          }
          
          // Check if it's a long-running initialization stage
          if (LONG_RUNNING_STAGES.includes(newStage.toLowerCase())) {
            setInitializationStage(newStage);
          } else {
            setInitializationStage(null);
          }
        }
      } catch (err) {
        // Silently ignore polling errors
      }
    }, 200);

    return () => clearInterval(pollInterval);
  }, [loading, apiUrl, requestId]);

  useEffect(() => {
    if (!loading || !requestId) return;
    let cancelled = false;
    const pollResult = async () => {
      try {
        const resp = await fetch(`${apiUrl}/api/result?request_id=${encodeURIComponent(requestId)}`);
        if (!resp.ok) return;
        const data = await resp.json();
        if (cancelled) return;
        if (data.status === "done") {
          setResult(data.result as AskResult);
          setLoading(false);
          return;
        }
        if (data.status === "error") {
          setError(data.error || "Something went wrong");
          setLoading(false);
          return;
        }
      } catch (_err) {
        // ignore transient errors
      }
    };
    const t = setInterval(pollResult, 500);
    pollResult();
    return () => {
      cancelled = true;
      clearInterval(t);
    };
  }, [loading, requestId, apiUrl]);

  // Handle column resizing
  useEffect(() => {
    if (!isDragging) return;

    const handleMouseMove = (e: MouseEvent) => {
      const container = document.getElementById("results-container");
      if (!container) return;

      const rect = container.getBoundingClientRect();
      const newLeftWidth = ((e.clientX - rect.left) / rect.width) * 100;

      if (isDragging === "left-center" && newLeftWidth > 20 && newLeftWidth < 50) {
        setLeftColWidth(newLeftWidth);
      } else if (isDragging === "center-right") {
        // Calculate from the right side of the container
        const newRightWidth = ((rect.right - e.clientX) / rect.width) * 100;
        if (newRightWidth > 20 && newRightWidth < 50) {
          setRightColWidth(newRightWidth);
        }
      }
    };

    const handleMouseUp = () => {
      setIsDragging(null);
    };

    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp);

    return () => {
      document.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseup", handleMouseUp);
    };
  }, [isDragging]);

  // Handle escape key for modals
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape" && modal.type) {
        setModal({ type: null });
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [modal]);

  // Handle mouse movement for header gradient effect
  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      const header = document.querySelector('[class*="from-blue-600"]');
      if (header) {
        const rect = header.getBoundingClientRect();
        const x = ((e.clientX - rect.left) / rect.width) * 100;
        const y = ((e.clientY - rect.top) / rect.height) * 100;
        (header as HTMLElement).style.setProperty('--mouse-x', `${x}%`);
        (header as HTMLElement).style.setProperty('--mouse-y', `${y}%`);
      }
    };

    document.addEventListener("mousemove", handleMouseMove);
    return () => document.removeEventListener("mousemove", handleMouseMove);
  }, []);

  async function submitQuestion(value?: string) {
    const q = (value ?? question).trim();
    if (!q) return;
    setLoading(true);
    setError(null);
    setResult(null);
    setRequestId(null);
    setCurrentStage("planning"); // Reset to planning stage
    try {
      const resp = await fetch(`${apiUrl}/api/ask?async=1`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: q }),
      });
      if (!resp.ok) {
        const msg = await resp.text();
        throw new Error(msg || "Request failed");
      }
      const data = (await resp.json()) as AskResult;
      console.log("API Response:", data);
      if (data.request_id) {
        setRequestId(data.request_id);
      } else {
        throw new Error("Missing request_id from async response");
      }
    } catch (err: any) {
      console.error("API Error:", err);
      setError(err?.message || "Something went wrong");
    } finally {
      // keep loading until /api/result resolves
    }
  }

  

  const frames = result?.frames || {};
  const frameKeys = Object.keys(frames);
  const graphFrameKeys = frameKeys.filter((key) => key.startsWith("graph:"));
  const activeRows = activeFrame ? frames[activeFrame] || [] : result?.rows || [];
  const activeGraphRows = activeGraphFrame ? frames[activeGraphFrame] || [] : [];
  const kpis = (result?.kpis || []).map((kpi) => ({
    label: kpi.label || kpi.title || "",
    value: kpi.value,
    unit: kpi.unit || kpi.sub || "",
  }));
  const narrative = (result?.narrative || result?.insights || "").trim();
  const reasonerResults = result?.reasoner_results || null;
  const activeReasonerResults = useMemo(() => {
    if (!reasonerResults) return null;
    if (activeFrame && reasonerResults[activeFrame]) return reasonerResults[activeFrame];
    const firstKey = Object.keys(reasonerResults)[0];
    return firstKey ? reasonerResults[firstKey] : null;
  }, [reasonerResults, activeFrame]);

  const summarizeDrilldowns = (drilldowns: any) => {
    if (!drilldowns) return [];
    if (drilldowns.steps) {
      return Object.entries(drilldowns.steps).map(([stepId, payload]: any) => {
        const rows = payload?.rows || [];
        const recordCount = rows.reduce((acc: number, row: any) => acc + ((row?.records || []).length || 0), 0);
        return { label: stepId, sources: rows.length, records: recordCount };
      });
    }
    if (drilldowns.machines) {
      return [{ label: "machines", sources: drilldowns.machines.length, records: 0 }];
    }
    if (drilldowns.audits) {
      return [{ label: "audits", sources: drilldowns.audits.length, records: 0 }];
    }
    return [];
  };

  useEffect(() => {
    const text = (stageThinking || "").trim();
    setThinkingVisible(!!text && loading && currentStage.toLowerCase() !== "done");
  }, [stageThinking, loading, currentStage]);
  
  return (
    <div className="relative h-screen flex flex-col bg-gradient-to-br from-slate-50 via-blue-50 to-slate-100 overflow-hidden">
      {/* Background orbs */}
      <div
        className="absolute -top-40 -left-40 w-96 h-96 opacity-20 blur-3xl"
        style={{
          background: "radial-gradient(circle, #0a37c4 0%, transparent 70%)",
        }}
      />
      <div
        className="absolute -bottom-20 -right-32 w-96 h-96 opacity-15 blur-3xl"
        style={{
          background: "radial-gradient(circle, #1d4ed8 0%, transparent 70%)",
        }}
      />

      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="relative z-10 backdrop-blur-md bg-gradient-to-r from-blue-600 via-blue-700 to-blue-600 shadow-2xl overflow-hidden group"
        style={{
          clipPath: "polygon(0 0, 100% 0, 100% calc(100% - 12px), 0 100%)"
        }}
      >
        {/* Animated gradient background */}
        <div className="absolute inset-0 bg-gradient-to-r from-cyan-400/30 via-transparent to-blue-400/20 opacity-0 group-hover:opacity-100 transition-opacity duration-700" />
        
        {/* Animated light effect on hover - interactive glow */}
        <div className="absolute inset-0 opacity-0 group-hover:opacity-30 transition-opacity duration-500 pointer-events-none" style={{
          background: "radial-gradient(circle at var(--mouse-x, 50%) var(--mouse-y, 50%), rgba(255,255,255,0.4) 0%, transparent 60%)"
        }} />
        
        {/* Animated accent line */}
        <motion.div 
          className="absolute bottom-0 left-0 h-1 bg-gradient-to-r from-cyan-300 via-blue-300 to-transparent"
          initial={{ scaleX: 0 }}
          animate={{ scaleX: 1 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          style={{ width: "100%", transformOrigin: "left" }}
        />
        
        <div className="max-w-7xl mx-auto px-8 py-8 relative z-10">
          <div className="flex items-center justify-between">
            <div className="flex flex-col gap-1">
              <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
                className="flex items-center gap-2"
              >
                <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-cyan-300 to-blue-400 flex items-center justify-center shadow-lg">
                  <span className="text-lg font-bold text-blue-900">◆</span>
                </div>
                <div className="flex flex-col">
                  <h1 className="text-4xl font-display font-bold text-white drop-shadow-lg tracking-tight">AI Analyst</h1>
                  <p className="text-xs font-semibold text-cyan-100 tracking-widest uppercase">Intelligence Platform</p>
                </div>
              </motion.div>
            </div>
            <motion.div 
              className="text-right"
              initial={{ opacity: 0, x: 10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
            >
              <p className="text-sm font-medium text-blue-100">Powered by O3</p>
              <motion.div 
                className="h-0.5 bg-gradient-to-r from-transparent via-cyan-300 to-transparent mt-2"
                animate={{ scaleX: [0, 1, 0] }}
                transition={{ duration: 2.5, repeat: Infinity }}
                style={{ transformOrigin: "center" }}
              />
            </motion.div>
          </div>
        </div>
      </motion.div>

      {/* Main Content Area */}
      <div className="relative z-10 overflow-hidden flex-1 flex flex-col">
        {!result ? (
          // Empty State
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="flex items-center justify-center px-6 py-8 min-h-0"
          >
            <div className="max-w-2xl w-full">
              <div className="text-center mb-4">
                <h2 className="text-4xl font-display font-bold text-slate-900 mb-2">
                  What would you like to analyze?
                </h2>
                <p className="text-lg text-slate-600">
                  Ask questions about performance, revenue, sentiment, and more.
                </p>
              </div>

              {/* Quick Examples */}
              <div className="grid grid-cols-1 gap-2 mb-4">
                {EXAMPLES.map((example) => (
                  <motion.button
                    key={example}
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => {
                      setQuestion(example);
                      submitQuestion(example);
                    }}
                    className="text-left p-3 rounded-xl bg-white/60 hover:bg-white border border-white/80 text-slate-700 font-medium transition-all hover:shadow-lg"
                  >
                    {example}
                  </motion.button>
                ))}
              </div>

              {error && (
                <div className="mb-4 p-4 rounded-lg bg-red-50 border border-red-200">
                  <p className="text-sm text-red-700">{error}</p>
                </div>
              )}
            </div>
          </motion.div>
        ) : (
          // Results View - Responsive Layout (Mobile: Stack, Tablet: 2 col, Desktop: 3 col)
          <div id="results-container" className="h-full flex flex-col md:flex-row gap-0 overflow-hidden relative w-full">
            {/* Mobile Tab Switcher */}
            <div className="md:hidden flex border-b border-white/40 bg-white/30 backdrop-blur-sm">
              {[
                { tab: "data" as const, label: "KPI & Data" },
                { tab: "summary" as const, label: "Summary" },
                { tab: "chart" as const, label: "Chart" },
              ].map((item) => (
                <motion.button
                  key={item.tab}
                  onClick={() => setMobileTab(item.tab)}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  className={`flex-1 px-4 py-3 text-sm font-semibold transition-all ${
                    mobileTab === item.tab
                      ? "text-blue-600 border-b-2 border-blue-600"
                      : "text-slate-600 hover:text-slate-800"
                  }`}
                >
                  {item.label}
                </motion.button>
              ))}
            </div>

            {/* Left Column - KPIs & Dataset - Only show on tablet+ or mobile "data" tab */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5 }}
              style={{ 
                width: viewportWidth < 768 ? "100%" : viewportWidth < 1024 ? "50%" : `${leftColWidth}%`,
                maxHeight: "100%",
                display: viewportWidth < 768 && mobileTab !== "data" ? "none" : "flex"
              }}
              className="overflow-y-auto border-r border-white/40 border-b md:border-b-0 flex flex-col"
            >
              <div className="px-6 py-4 space-y-4 flex-1">
                {/* KPI Cards */}
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: 0.1 }}
                >
                  <p className="text-xs font-semibold tracking-widest text-slate-500 uppercase mb-4">Metrics</p>
                  <div className="space-y-3">
                    {kpis.length ? (
                      kpis.map((kpi, idx) => (
                        <motion.div
                          key={`${kpi.label}-${idx}`}
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          transition={{ duration: 0.4, delay: 0.15 + idx * 0.08 }}
                        >
                          <KpiCard label={kpi.label || ""} value={kpi.value} unit={kpi.unit} />
                        </motion.div>
                      ))
                    ) : (
                      <p className="text-sm text-slate-500">No metrics</p>
                    )}
                  </div>
                </motion.div>

                {/* Dataset Selector & Table */}
                {frameKeys.length > 0 && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: 0.3 }}
                    className="flex flex-col"
                  >
                    <label className="block text-xs font-semibold tracking-widest text-slate-500 uppercase mb-3">
                      Dataset
                    </label>
                    <select
                      value={activeFrame}
                      onChange={(e) => setActiveFrame(e.target.value)}
                      className="w-full px-3 py-2 rounded-lg border border-white/50 bg-white/40 text-sm font-medium mb-4 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                      {frameKeys.map((key) => (
                        <option key={key} value={key}>
                          {key}
                        </option>
                      ))}
                    </select>
                    {activeRows.length > 0 && (
                      <div className="flex-1 overflow-hidden bg-white/40 rounded-lg border border-white/50 min-h-64 relative group">
                        <div className="h-64 overflow-y-auto">
                          <ResultTable rows={activeRows || []} variant="flat" showTitle={false} />
                        </div>
                        <motion.button
                          whileHover={{ scale: 1.05 }}
                          whileTap={{ scale: 0.95 }}
                          onClick={() => setModal({ type: "dataset" })}
                          className="absolute top-2 right-2 bg-blue-500/80 hover:bg-blue-600 text-white px-3 py-1 text-xs font-semibold rounded-lg opacity-0 group-hover:opacity-100 transition-opacity duration-200"
                        >
                          Expand
                        </motion.button>
                      </div>
                    )}
                  </motion.div>
                )}

                {graphFrameKeys.length > 0 && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: 0.35 }}
                    className="flex flex-col"
                  >
                    <label className="block text-xs font-semibold tracking-widest text-slate-500 uppercase mb-3">
                      Graph Results
                    </label>
                    <select
                      value={activeGraphFrame}
                      onChange={(e) => setActiveGraphFrame(e.target.value)}
                      className="w-full px-3 py-2 rounded-lg border border-white/50 bg-white/40 text-sm font-medium mb-4 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                      {graphFrameKeys.map((key) => (
                        <option key={key} value={key}>
                          {key.replace("graph:", "")}
                        </option>
                      ))}
                    </select>
                    {activeGraphRows.length > 0 ? (
                      <div className="flex-1 overflow-hidden bg-white/40 rounded-lg border border-white/50 min-h-48">
                        <div className="h-48 overflow-y-auto">
                          <ResultTable rows={activeGraphRows || []} variant="flat" showTitle={false} />
                        </div>
                      </div>
                    ) : (
                      <p className="text-sm text-slate-500">No graph results.</p>
                    )}
                  </motion.div>
                )}
              </div>
            </motion.div>

            {/* Resize Handle - Left/Center - Hidden on Mobile */}
            <div
              onMouseDown={() => setIsDragging("left-center")}
              className={`hidden md:block w-1 bg-gradient-to-b from-transparent via-white/10 to-transparent hover:bg-gradient-to-b hover:from-blue-400/30 hover:via-blue-500/60 hover:to-blue-400/30 cursor-col-resize transition-all duration-200 hover:shadow-lg ${
                isDragging === "left-center" ? "bg-gradient-to-b from-blue-400/40 via-blue-500/80 to-blue-400/40 shadow-lg" : ""
              }`}
            />

            {/* Center Column - Summary/Insights - Only show on tablet+ or mobile "summary" tab */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              style={{ 
                flex: viewportWidth < 768 ? 1 : 1,
                width: viewportWidth < 768 ? "100%" : viewportWidth < 1024 ? "50%" : "auto",
                maxHeight: viewportWidth < 768 ? "100%" : "100%",
                display: viewportWidth < 768 && mobileTab !== "summary" ? "none" : "flex"
              }}
              className="overflow-y-auto border-r border-white/40 border-b md:border-b-0 flex flex-col bg-gradient-to-br from-white/50 to-blue-50/30"
            >
              <div className="px-6 py-4 flex-1 overflow-y-auto">
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: 0.2 }}
                  className="h-full"
                >
                  <p className="text-xs font-semibold tracking-widest text-slate-500 uppercase mb-4 sticky top-0">Summary</p>
                  <SummaryRenderer content={narrative} />
                </motion.div>
              </div>
            </motion.div>

            {/* Resize Handle - Center/Right - Hidden on Mobile/Tablet */}
            <div
              onMouseDown={() => setIsDragging("center-right")}
              className={`hidden lg:block w-1 bg-gradient-to-b from-transparent via-white/10 to-transparent hover:bg-gradient-to-b hover:from-blue-400/30 hover:via-blue-500/60 hover:to-blue-400/30 cursor-col-resize transition-all duration-200 hover:shadow-lg ${
                isDragging === "center-right" ? "bg-gradient-to-b from-blue-400/40 via-blue-500/80 to-blue-400/40 shadow-lg" : ""
              }`}
            />

            {/* Right Column - Visualization - Only show on desktop or mobile "chart" tab */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              style={{ 
                width: viewportWidth < 1024 ? "100%" : `${rightColWidth}%`,
                minWidth: 0,
                maxHeight: "100%",
                display: viewportWidth < 768 && mobileTab !== "chart" ? "none" : "flex"
              }}
              className="overflow-y-auto relative group flex flex-col"
            >
              <div className="px-6 py-4 flex-1 flex flex-col">
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: 0.3 }}
                  className="flex-1 flex flex-col"
                >
                  <p className="text-xs font-semibold tracking-widest text-slate-500 uppercase mb-4">Visualization</p>
                  {result?.chart && Array.isArray(result.chart.data) && result.chart.layout ? (
                    <div className="relative flex-1 flex flex-col">
                      <div className="flex-1 overflow-hidden">
                        <ChartPanel chart={result.chart} title="" />
                      </div>
                      <motion.button
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        onClick={() => setModal({ type: "chart" })}
                        className="absolute top-8 right-4 bg-blue-500/80 hover:bg-blue-600 text-white px-3 py-1 text-xs font-semibold rounded-lg opacity-0 group-hover:opacity-100 transition-opacity duration-200"
                      >
                        Fullscreen
                      </motion.button>
                    </div>
                  ) : (
                    <div className="flex-1 flex items-center justify-center bg-white/40 rounded-lg border border-white/50">
                      <div className="text-center">
                        <p className="text-slate-500 text-sm mb-2">Chart visualization in progress</p>
                        <p className="text-slate-400 text-xs">LLM is generating your chart...</p>
                      </div>
                    </div>
                  )}
                </motion.div>
              </div>
            </motion.div>

            {/* Fullscreen Modal - Dataset */}
            {modal.type === "dataset" && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={() => setModal({ type: null })}
                className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[100]"
              >
                <motion.div
                  initial={{ scale: 0.9, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0.9, opacity: 0 }}
                  onClick={(e) => e.stopPropagation()}
                  className="w-11/12 h-5/6 bg-white/95 backdrop-blur-sm rounded-2xl border border-white/80 shadow-2xl flex flex-col"
                >
                  <div className="flex items-center justify-between p-6 border-b border-white/40">
                    <h2 className="text-xl font-bold text-slate-900">Dataset - {activeFrame}</h2>
                    <motion.button
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.9 }}
                      onClick={() => setModal({ type: null })}
                      className="text-slate-500 hover:text-slate-700 text-2xl font-light"
                    >
                      ×
                    </motion.button>
                  </div>
                  <div className="flex-1 overflow-y-auto p-6">
                    <ResultTable rows={activeRows || []} variant="flat" showTitle={false} />
                  </div>
                </motion.div>
              </motion.div>
            )}

            {/* Fullscreen Modal - Chart */}
            {modal.type === "chart" && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={() => setModal({ type: null })}
                className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[100]"
              >
                <motion.div
                  initial={{ scale: 0.9, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0.9, opacity: 0 }}
                  onClick={(e) => e.stopPropagation()}
                  className="w-11/12 h-5/6 bg-white/95 backdrop-blur-sm rounded-2xl border border-white/80 shadow-2xl flex flex-col"
                >
                  <div className="flex items-center justify-between p-6 border-b border-white/40">
                    <h2 className="text-xl font-bold text-slate-900">Visualization</h2>
                    <motion.button
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.9 }}
                      onClick={() => setModal({ type: null })}
                      className="text-slate-500 hover:text-slate-700 text-2xl font-light"
                    >
                      ×
                    </motion.button>
                  </div>
                  <div className="flex-1 overflow-hidden p-6 flex items-center justify-center">
                    {result?.chart && Object.keys(result.chart).length > 0 ? (
                      <div style={{ width: "100%", height: "100%" }}>
                        <ChartPanel chart={result.chart} title="" />
                      </div>
                    ) : null}
                  </div>
                </motion.div>
              </motion.div>
            )}
          </div>
        )}

        {/* Initialization Modal - Long Running Stages */}
        {initializationStage && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-[150]"
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 10 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 10 }}
              transition={{ type: "spring", damping: 20, stiffness: 300 }}
              className="bg-white rounded-2xl shadow-2xl p-8 max-w-sm w-full mx-6"
            >
              <div className="text-center">
                <div className="mb-6 flex justify-center">
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                    className="w-12 h-12 border-4 border-blue-200 border-t-blue-600 rounded-full"
                  />
                </div>
                <h3 className="text-lg font-bold text-slate-900 mb-2">
                  {STAGE_MESSAGES[initializationStage.toLowerCase()] || initializationStage}
                </h3>
                <p className="text-sm text-slate-500 mb-6">
                  This may take a moment. Please be patient...
                </p>
                <div className="w-full bg-slate-200 rounded-full h-1.5 overflow-hidden">
                  <motion.div
                    animate={{ x: ["-100%", "100%"] }}
                    transition={{ duration: 1.5, repeat: Infinity }}
                    className="h-full bg-gradient-to-r from-transparent via-blue-500 to-transparent w-1/4"
                  />
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}

        {/* Loading State */}
        {loading && !initializationStage && (
          <div className="absolute inset-0 bg-black/10 backdrop-blur-sm flex items-center justify-center z-50">
            <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full mx-6">
              <p className="text-sm text-slate-500 mb-2">{"Working"}</p>
              <p className="text-slate-800 font-medium mb-6">{question || "Processing your question..."}</p>
              {stageThinking && thinkingVisible && (
                <motion.div
                  initial={{ opacity: 0, y: -6 }}
                  animate={{
                    opacity: 1,
                    y: 0,
                  }}
                  transition={{ duration: 0.4 }}
                  className="mb-4 rounded-lg border border-blue-200/60 bg-blue-50/70 px-3 py-2 text-xs text-blue-800"
                >
                  <span className="mr-2 inline-block h-2 w-2 animate-pulse rounded-full bg-blue-500 align-middle" />
                  <span className="font-semibold mr-1">Thinking:</span>
                  <span className="italic">{stageThinking}</span>
                  <span className="ml-1 inline-block animate-pulse">...</span>
                </motion.div>
              )}
              <div className="flex flex-wrap gap-2">
                {STAGES.map((stage) => {
                  const stageMap: Record<string, string> = {
                    planning: "planning",
                    fetching: "fetching",
                    linking: "linking",
                    summarizing: "summarizing",
                  };
                  const isActive = stageMap[stage.toLowerCase()] === currentStage.toLowerCase();
                  return (
                    <motion.span
                      key={stage}
                      animate={{
                        scale: isActive ? 1.1 : 1,
                        backgroundColor: isActive ? "#0a37c4" : "#f1f5f9",
                      }}
                      className="px-3 py-1 text-xs font-medium rounded-full text-slate-600 transition-colors"
                      style={{
                        color: isActive ? "white" : "#64748b",
                      }}
                    >
                      {stage}
                    </motion.span>
                  );
                })}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Floating Input Bar - Bottom */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.2 }}
        className="relative z-20 m-4 rounded-full bg-gradient-to-r from-white/95 to-white/90 backdrop-blur-md border border-white/90 shadow-2xl hover:shadow-blue-400/20 hover:border-white transition-all"
      >
        <form
          onSubmit={(e) => {
            e.preventDefault();
            submitQuestion();
          }}
          className="flex items-center gap-3 px-6 py-3.5"
        >
          <input
            type="text"
            placeholder="Ask a question..."
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            className="flex-1 bg-transparent text-slate-800 placeholder:text-slate-400 focus:outline-none text-sm font-medium"
            disabled={loading}
          />
          <button
            type="submit"
            disabled={loading || !question.trim()}
            className="px-6 py-2.5 rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white text-sm font-bold shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed disabled:shadow-none transition-all whitespace-nowrap"
          >
            {loading ? "Analyzing..." : "Analyze"}
          </button>
        </form>
      </motion.div>
    </div>
  );
}
